// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package images

import "strconv"

/// The background and overlay the client draws around blueprints, relics and reactions.
type Frame byte

const (
	FrameNone      Frame = 0
	FrameBlueprint Frame = 1
	FrameRelic     Frame = 2
	FrameReaction  Frame = 3
)

var EnumNamesFrame = map[Frame]string{
	FrameNone:      "None",
	FrameBlueprint: "Blueprint",
	FrameRelic:     "Relic",
	FrameReaction:  "Reaction",
}

var EnumValuesFrame = map[string]Frame{
	"None":      FrameNone,
	"Blueprint": FrameBlueprint,
	"Relic":     FrameRelic,
	"Reaction":  FrameReaction,
}

func (v Frame) String() string {
	if s, ok := EnumNamesFrame[v]; ok {
		return s
	}
	return "Frame(" + strconv.FormatInt(int64(v), 10) + ")"
}
