// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package images

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// The overlay is drawn additively.
type FrameImages struct {
	_tab flatbuffers.Struct
}

func (rcv *FrameImages) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FrameImages) Table() flatbuffers.Table {
	return rcv._tab.Table
}

/// Index into Images.images.
func (rcv *FrameImages) Background() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
/// Index into Images.images.
func (rcv *FrameImages) MutateBackground(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

/// Index into Images.images.
func (rcv *FrameImages) Overlay() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(2))
}
/// Index into Images.images.
func (rcv *FrameImages) MutateOverlay(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(2), n)
}

func CreateFrameImages(builder *flatbuffers.Builder, background uint16, overlay uint16) flatbuffers.UOffsetT {
	builder.Prep(2, 4)
	builder.PrependUint16(overlay)
	builder.PrependUint16(background)
	return builder.Offset()
}
