// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package images

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// Stored as images/<hash in 16 lowercase hex digits>.webp. An unchanged image
/// keeps its hash between releases.
type Image struct {
	_tab flatbuffers.Struct
}

func (rcv *Image) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Image) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *Image) Hash() uint64 {
	return rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *Image) MutateHash(n uint64) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func CreateImage(builder *flatbuffers.Builder, hash uint64) flatbuffers.UOffsetT {
	builder.Prep(8, 8)
	builder.PrependUint64(hash)
	return builder.Offset()
}
