// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package images

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type KeyedImage struct {
	_tab flatbuffers.Struct
}

func (rcv *KeyedImage) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *KeyedImage) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *KeyedImage) Id() int32 {
	return rcv._tab.GetInt32(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *KeyedImage) MutateId(n int32) bool {
	return rcv._tab.MutateInt32(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

/// Index into Images.images.
func (rcv *KeyedImage) Image() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(4))
}
/// Index into Images.images.
func (rcv *KeyedImage) MutateImage(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(4), n)
}

func CreateKeyedImage(builder *flatbuffers.Builder, id int32, image uint16) flatbuffers.UOffsetT {
	builder.Prep(4, 8)
	builder.Pad(2)
	builder.PrependUint16(image)
	builder.PrependInt32(id)
	return builder.Offset()
}
