// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package images

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// Drawn bottom to top: frame background, icon, frame overlay, marker.
type TypeIcon struct {
	_tab flatbuffers.Struct
}

func (rcv *TypeIcon) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TypeIcon) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *TypeIcon) TypeId() int32 {
	return rcv._tab.GetInt32(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *TypeIcon) MutateTypeId(n int32) bool {
	return rcv._tab.MutateInt32(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

/// Index into Images.images.
func (rcv *TypeIcon) Icon() uint16 {
	return rcv._tab.GetUint16(rcv._tab.Pos + flatbuffers.UOffsetT(4))
}
/// Index into Images.images.
func (rcv *TypeIcon) MutateIcon(n uint16) bool {
	return rcv._tab.MutateUint16(rcv._tab.Pos+flatbuffers.UOffsetT(4), n)
}

/// Index into Images.meta_groups, or 255 for no marker.
func (rcv *TypeIcon) Marker() byte {
	return rcv._tab.GetByte(rcv._tab.Pos + flatbuffers.UOffsetT(6))
}
/// Index into Images.meta_groups, or 255 for no marker.
func (rcv *TypeIcon) MutateMarker(n byte) bool {
	return rcv._tab.MutateByte(rcv._tab.Pos+flatbuffers.UOffsetT(6), n)
}

func (rcv *TypeIcon) Frame() Frame {
	return Frame(rcv._tab.GetByte(rcv._tab.Pos + flatbuffers.UOffsetT(7)))
}
func (rcv *TypeIcon) MutateFrame(n Frame) bool {
	return rcv._tab.MutateByte(rcv._tab.Pos+flatbuffers.UOffsetT(7), byte(n))
}

func CreateTypeIcon(builder *flatbuffers.Builder, typeId int32, icon uint16, marker byte, frame Frame) flatbuffers.UOffsetT {
	builder.Prep(4, 8)
	builder.PrependByte(byte(frame))
	builder.PrependByte(marker)
	builder.PrependUint16(icon)
	builder.PrependInt32(typeId)
	return builder.Offset()
}
