// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package images

import (
	"bytes"
	flatbuffers "github.com/google/flatbuffers/go"
)

type UiTexture struct {
	_tab flatbuffers.Table
}

func GetRootAsUiTexture(buf []byte, offset flatbuffers.UOffsetT) *UiTexture {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UiTexture{}
	x.Init(buf, n+offset)
	return x
}

func FinishUiTextureBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsUiTexture(buf []byte, offset flatbuffers.UOffsetT) *UiTexture {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &UiTexture{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedUiTextureBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *UiTexture) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UiTexture) Table() flatbuffers.Table {
	return rcv._tab
}

/// The path below res:/ui/texture/, without extension.
func (rcv *UiTexture) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

/// The path below res:/ui/texture/, without extension.
func UiTextureKeyCompare(o1, o2 flatbuffers.UOffsetT, buf []byte) bool {
	obj1 := &UiTexture{}
	obj2 := &UiTexture{}
	obj1.Init(buf, flatbuffers.UOffsetT(len(buf))-o1)
	obj2.Init(buf, flatbuffers.UOffsetT(len(buf))-o2)
	return string(obj1.Name()) < string(obj2.Name())
}

func (rcv *UiTexture) LookupByKey(key string, vectorLocation flatbuffers.UOffsetT, buf []byte) bool {
	span := flatbuffers.GetUOffsetT(buf[vectorLocation-4:])
	start := flatbuffers.UOffsetT(0)
	bKey := []byte(key)
	for span != 0 {
		middle := span / 2
		tableOffset := flatbuffers.GetIndirectOffset(buf, vectorLocation+4*(start+middle))
		obj := &UiTexture{}
		obj.Init(buf, tableOffset)
		comp := bytes.Compare(obj.Name(), bKey)
		if comp > 0 {
			span = middle
		} else if comp < 0 {
			middle += 1
			start += middle
			span -= middle
		} else {
			rcv.Init(buf, tableOffset)
			return true
		}
	}
	return false
}

/// Index into Images.images.
func (rcv *UiTexture) Image() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

/// Index into Images.images.
func (rcv *UiTexture) MutateImage(n uint16) bool {
	return rcv._tab.MutateUint16Slot(6, n)
}

func UiTextureStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func UiTextureAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(name), 0)
}
func UiTextureAddImage(builder *flatbuffers.Builder, image uint16) {
	builder.PrependUint16Slot(1, image, 0)
}
func UiTextureEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
